version: '3'
services:
  mnist_classifier:
    build: .
    environment:
      - WANDB_API_KEY=c6e96b3d5ca654a8f7225e46a447e15ed0cde666
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"